<!DOCTYPE html>
<!--[if IE 8]>
    <html class="no-js lt-ie9" lang="en">
<![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title></title>

        <!--<link rel="stylesheet" href="/bundles/foundation-5.0.2/css/normalize.css" />
        <link rel="stylesheet" href="/bundles/foundation-5.0.2/css/foundation.css" />
        <link rel="stylesheet" href="/css/style.css" />

        <script src="/bundles/foundation-5.0.2/js/vendor/custom.modernizr.js"></script>-->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    </head>
    <body>
        <nav class="top-bar">
            <ul class="title-area">
                <li class="name">
                    <h1><a href="/">Title</a></h1>
                </li>
            </ul>

            <section class="top-bar-section">
                <ul class="right">
                    <li class="divider hide-for-small"></li>
                    <li><a href="/">HOME</a></li>
                    <li><a href="/about">ABOUT</a></li>
                    <li><a href="/pricing">PRICING</a></li>
                    <?php if (!$this->auth()->hasIdentity()): ?>
                        <li><a href="/login">LOGIN</a></li>
                        <li><a href="/signup">SIGNUP</a></li>
                    <?php else: ?>
                        <li><a href="/profile">PROFILE</a></li>
                        <li><a href="/logout">LOGOUT</a></li>
                    <?php endif; ?>
                    <li class="divider"></li>
                    <li class="has-form">
                        <form>
                            <div class="row collapse">
                                <div class="small-8 columns">
                                    <input type="text">
                                </div>
                                <div class="small-4 columns">
                                    <a href="#" class="alert button">Search</a>
                                </div>
                            </div>
                        </form>
                    </li>
                </ul>
            </section>
        </nav>

        <div class="graybar">
            <div><?php echo $this->title; ?></div>
        </div>

        <div id="content" style="clear:both;width:100%;padding-top:200px;float:left;">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>