<div id="fb-root"></div>

<div id="sliders-container">
    <!-- START REVOLUTION SLIDER 3.0.95 fullwidth mode -->
    <div id="rev_slider_3_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#ffffff;padding:0px;margin-top:0px;margin-bottom:0px;max-height:500px;">
        <div id="rev_slider_3_1" class="rev_slider fullwidthabanner" style="display:none;max-height:500px;height:500;">						
            <ul>
                <li data-transition="slideright" data-slotamount="7" data-masterspeed="2000" data-delay="30000" >
                    <img src="/wordpress/wp-content/plugins/revslider/images/transparent.png"  alt=""  data-fullwidthcentering="on">
                    <div class="tp-caption fade"
                         data-x="600" 
                         data-y="10"
                         data-speed="300" 
                         data-start="500" 
                         data-easing="easeOutExpo">
                        <img src="/wordpress/wp-content/uploads/2013/11/background_white_logo.png" alt="Logo">
                    </div>

                    <div class="tp-caption fade"
                         data-x="30" 
                         data-y="234"
                         data-speed="300" 
                         data-start="800" 
                         data-easing="easeOutExpo">
                        <img src="/wordpress/wp-content/uploads/2013/11/facebook_150px.png" alt="Facebook">
                    </div>

                    <div class="tp-caption fade"
                         data-x="176" 
                         data-y="234"
                         data-speed="300" 
                         data-start="1100" 
                         data-easing="easeOutExpo">
                        <img src="/wordpress/wp-content/uploads/2013/11/instagram_150px.png" alt="Instagram">					 					 </div>

                    <div class="tp-caption fade"
                         data-x="394" 
                         data-y="225"
                         data-speed="300" 
                         data-start="1400" 
                         data-easing="easeOutExpo">
                        <img src="/wordpress/wp-content/uploads/2013/11/pijl_150px.png" alt="Image 4">
                    </div>

                    <div class="tp-caption fade"
                         data-x="630" 
                         data-y="150"
                         data-speed="300" 
                         data-start="1700" 
                         data-easing="easeOutExpo">
                        <img src="/wordpress/wp-content/uploads/2013/11/krantje1.png" alt="krant">
                    </div>

                    <div class="tp-caption fade"
                         data-x="1059" 
                         data-y="224"
                         data-speed="300" 
                         data-start="2000" 
                         data-easing="easeOutExpo">
                        <img src="/wordpress/wp-content/uploads/2013/11/pijl_150px.png" alt="pijl2">
                    </div>

                    <div class="tp-caption fade"
                         data-x="1256" 
                         data-y="165"
                         data-speed="300" 
                         data-start="2300" 
                         data-easing="easeOutExpo">
                        <img src="/wordpress/wp-content/uploads/2013/11/opaoma_300px1.png" alt="OmaOpa">
                    </div>
                </li>
            </ul>
        </div>
    </div>				

    <script type="text/javascript">
        var tpj = jQuery;
        tpj.noConflict();
        var revapi3;
        tpj(document).ready(function() {
            if (tpj.fn.cssOriginal != undefined)
                tpj.fn.css = tpj.fn.cssOriginal;
            if (tpj('#rev_slider_3_1').revolution == undefined)
                revslider_showDoubleJqueryError('#rev_slider_3_1');
            else
                revapi3 = tpj('#rev_slider_3_1').show().revolution(
                {
                    delay: 90000,
                    startwidth: 1600,
                    startheight: 500,
                    hideThumbs: 200,
                    thumbWidth: 100,
                    thumbHeight: 50,
                    thumbAmount: 1,
                    navigationType: "none",
                    navigationArrows: "none",
                    navigationStyle: "round",
                    touchenabled: "on",
                    onHoverStop: "on",
                    navigationHAlign: "center",
                    navigationVAlign: "bottom",
                    navigationHOffset: 0,
                    navigationVOffset: 20,
                    soloArrowLeftHalign: "left",
                    soloArrowLeftValign: "center",
                    soloArrowLeftHOffset: 20,
                    soloArrowLeftVOffset: 0,
                    soloArrowRightHalign: "right",
                    soloArrowRightValign: "center",
                    soloArrowRightHOffset: 20,
                    soloArrowRightVOffset: 0,
                    shadow: 0,
                    fullWidth: "on",
                    fullScreen: "off",
                    stopLoop: "on",
                    stopAfterLoops: 0,
                    stopAtSlide: 1,
                    shuffle: "off",
                    hideSliderAtLimit: 0,
                    hideCaptionAtLimit: 0,
                    hideAllCaptionAtLilmit: 0,
                    startWithSlide: 0,
                    videoJsPath: "/wordpress/wp-content/plugins/revslider/rs-plugin/videojs/",
                    fullScreenOffsetContainer: ""
                });
        });	//ready
    </script>
<!-- END REVOLUTION SLIDER -->
</div>


<div id="main" class="" style="overflow:hidden !important;">
    <div class="avada-row" style="">
        <div id="content" class="full-width">
            <div id="post-2" class="post-2 page type-page status-publish hentry">
                <span class="entry-title" style="display: none;">welkom</span>
                <span class="updated" style="display: none;">November 30th, 2013</span>
                <span class="vcard" style="display: none;"><span class="fn"><a href="/wordpress/?author=1" title="Posts by balushops" rel="author">balushops</a></span></span>
                <div class="post-content">
                    <div class="demo-sep sep-none" style="margin-top:-25px;"></div>
                    <div class="fullwidth-box" style="background-color:#cfeae4;background-image:url();background-repeat:no-repeat;background-position:top left;background-attachment:scroll;border-top:1px solid #e5e4e4;border-bottom:1px solid #e5e4e4;padding-top:20px;padding-bottom:15px;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;">
                        <div class="avada-row">
                            <h1 style="text-align: center; font-size: 40px !important;">Wekelijkse familiemomenten, <span class="tooltip-shortcode"><strong>per post</strong><span class="popup">
                                <span class="holder">
                                    <span>Een herkenbaar medium</span>
                                </span>
                            </span></span>, voor oma &#038; opa</h1>
                            <p style="text-align: center;"><a class="button large default" href="#" id="fb-login">Sign up</a></p>
                        </div>
                    </div>
                    <div class="demo-sep sep-" style="margin-top:40px;margin-bottom:40px"></div>
                    <div class="one_half">
                        <style type='text/css'>
                            #imageframe-1.imageframe{float:;}
                            #imageframe-1.imageframe img{border:5px solid #FFFFFF;}
                            #imageframe-1.imageframe-glow img{
                                -moz-box-shadow: 0 0 3px rgba(0,0,0,.3); /* outer glow */
                                -webkit-box-shadow: 0 0 3px rgba(0,0,0,.3); /* outer glow */
                                box-shadow: 0 0 3px rgba(0,0,0,.3); /* outer glow */
                            }
                            #imageframe-1.imageframe-dropshadow img{
                                -moz-box-shadow: 2px 3px 7px rgba(0,0,0,.3); /* drop shadow */
                                -webkit-box-shadow: 2px 3px 7px rgba(0,0,0,.3); /* drop shadow */
                                box-shadow: 2px 3px 7px rgba(0,0,0,.3); /* drop shadow */
                            }
                        </style>
                        <span id="imageframe-1" class="imageframe imageframe-dropshadow">
                            <img alt="Voorbeeld van de familiekrant" src="/wordpress/wp-content/uploads/2013/11/teaser_noborder.png" /><br />
                        </span>
                    </div>
                    <div class="one_half last">
                        Een groot deel van ons leven wordt gedeeld op Facebook en Instagram. Momenten zoals muziekoptredens, sportwedstrijden, de eerste foto’s van een pasgeboren kleinkind, zonnige vakanties, kleinkinderen met een nieuw lief, of domweg een gebroken been. </p>
                        <p>Momenten om te koesteren die oma en opa al te vaak missen. Onze grootouders zijn helaas niet altijd op de hoogte van wat zich allemaal afspeelt in het leven van de familieleden. Stiekem zijn oma of opa daardoor toch een beetje eenzaam.</p>
                        <p>Familienieuws brengt voor jouw oma en opa elke week een krantje via de postbode. Informatie over de passie, de successen en de leefwereld van de familie, op het moment dat het plaatsvind. </p>
                        <p>Kleurrijke foto’s van lachende kleinkinderen, zonnige vakantiefoto’s en statusupdates over de kleine dingen des levens. <strong>Op een herkenbare manier voor de grootouders: per post en op papier.</strong></p>
                        <p>Schrijf je nu in en zorg ervoor dat je gespreksstof hebt de volgende keer dat je op de koffie komt.<br />
                    </div><div class="clearboth"></div>
                    <div class="demo-sep sep-" style="margin-top:40px;margin-bottom:40px"></div>
                    <div class="fullwidth-box" style="background-color:;background-image:url();background-repeat:no-repeat;background-position:top left;background-attachment:scroll;border-top:0px solid #f6f6f6;border-bottom:0px solid #f6f6f6;padding-top:0px;padding-bottom:0px;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;">
                        <div class="avada-row">
                            <style type='text/css'>
                                #content-boxes-1 article.col{background-color:#fff !important;}
                                #content-boxes-1 .fontawesome-icon.circle-yes{color:#50cbf4 !important;background-color:#fff !important;border:1px solid #50cbf4 !important;}
                            </style>
                            <section class="clearfix columns content-boxes content-boxes-icon-boxed columns-2" id="content-boxes-1">
                                <article class="col">
                                    <div class="heading heading-and-icon">
                                        <i class="fontawesome-icon medium circle-yes icon-trash" ></i>
                                        <h2>Foto's verbergen</h2>
                                    </div>
                                    <div class="col-content-container ">Niet elke foto is bestemd voor je oma of opa. Bepaal zelf de unieke familiemomenten. Voeg<span class="tooltip-shortcode"><strong> #notforgranny</strong><span class="popup">
                                        <span class="holder"><span>Hashtag voor op Facebook of Instagram</span></span>
                                        </span></span> toe aan je foto&#8217;s en oma en opa zullen denken dat je een engeltje bent.
                                    </div></article>
                                    <article class="col last"><div class="heading heading-and-icon"><i class="fontawesome-icon medium circle-yes icon-money" ></i><h2>1 koffie per week</h2></div><div class="col-content-container ">Voor de prijs van één koffie krijgen oma en opa wekelijks een Familienieuws krantje. Een abonnement van Familienieuws kost namelijk: 3 maanden: €30 6 maanden: €50<span class="tooltip-shortcode"><strong>12 maanden: €100</strong><span class="popup">
                                        <span class="holder">
                                            <span>2 maanden gratis</span>
                                        </span>
                                    </span></span></div>
                                </article>
                            </section>
                            <style type='text/css'>
                                #content-boxes-2 article.col{background-color:#fff !important;}
                                #content-boxes-2 .fontawesome-icon.circle-yes{color:#50cbf4 !important;background-color:#fff !important;border:1px solid #50cbf4 !important;}
                            </style>
                            <section class="clearfix columns content-boxes content-boxes-icon-boxed columns-1" id="content-boxes-2">
                                <article class="col">
                                    <div class="heading heading-and-icon">
                                        <i class="fontawesome-icon medium circle-yes icon-gears" ></i><h2>Hoe werkt het?</h2>
                                    </div>
                                    <div class="col-content-container ">De familieleden melden zich aan met Facebook waaruit de familiemomenten verzameld worden. Wekelijks wordt dan het ‘Familienieuws-krantje’ samengesteld. Enkel relevante foto&#8217;s voor Oma en Opa over <span class="tooltip-shortcode"><strong>de familieleden</strong><span class="popup">
                                                <span class="holder">
                                                    <span>maar ook vrienden/het lief/..., iedereen die je zelf selecteert</span>
                                                </span>
                                            </span></span> worden automatisch online gekozen uit de albums van Facebook en Instagram. FamilieNieuws heeft een unieke formule ontwikkeld dat een selectie maakt van de mooiste familie momenten en die rangschikt naar relevantie voor de grootouders.</div></article>
                            </section>
                        </div></div>
                    <div class="fullwidth-box" style="background-color:#cfeae4;background-image:url();background-repeat:no-repeat;background-position:top left;background-attachment:scroll;border-top:1px solid #e5e4e4;border-bottom:1px solid #e5e4e4;padding-top:20px;padding-bottom:15px;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;"><div class="avada-row">
                            <h1 style="text-align: center; font-size: 40px !important;">Wekelijkse familiemomenten, <span class="tooltip-shortcode"><strong>per post</strong><span class="popup">
                                        <span class="holder">
                                            <span>Een herkenbaar medium</span>
                                        </span>
                                    </span></span>, voor oma &#038; opa</h1>
                            <p style="text-align: center;"><a class="button large default" href="#" id="fb-login">Sign up</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
var settings = {
    app_id      : '<?php echo $this->config['facebook']['app_id']; ?>',
    app_redirect: '<?php echo $this->config['facebook']['callback_url']; ?>',
    app_scope   : '<?php echo $this->config['facebook']['scope']; ?>'
};
</script>
<script src="/js/facebook.js"></script>