<div class="row">
    <div class="large-4 large-offset-4 columns">
        <?php echo $this->partial('/partial/flashmessages'); ?>
    </div>
</div>

<div class="row">
    <div class="large-4 large-offset-4 columns">
        <p>Are you sure you want to delete this connector?</p>
    </div>
</div>

<div class="row">
    <div class="large-4 large-offset-4 columns">
        <a class="medium button prefix" href="/connector/delete/connectorId/<?php echo $this->connector->getId(); ?>/confirm/1">delete but keep existing feeds</a>
        <a class="medium button prefix" href="/connector/delete/connectorId/<?php echo $this->connector->getId(); ?>/confirm/2">delete and remove existing feeds</a>
        <a class="medium button prefix" href="/connector/index/timelineId/<?php echo $this->connector->getTimeline()->getId(); ?>">cancel</a>
    </div>
</div>