<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId   : '<?php echo $this->config['facebook']['app_id']; ?>',
            status  : true,
            xfbml   : true
        });
    };

    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    function ConnectorFacebook() {
        FB.login(function(response) {
            if (response.authResponse) {
                window.location = "/connector/facebook?access_token=" + response.authResponse.accessToken;
            } else {
                console.log('User cancelled login or did not fully authorize.');
            }
        }, {scope: 'email,publish_stream,status_update,friends_online_presence,user_birthday,user_location,user_work_history'});
    }
</script>

<script type="text/javascript">
    var Connector = (function() {
        function Connector(url) {
            this.url = url;
        }
        Connector.prototype.exec = function() {
            var self = this,
                    params = 'location=0,status=0,width=800,height=600';

            this.connector_window = window.open(this.url, 'connector', params);

            this.interval = window.setInterval((function() {
                if (self.connector_window.closed) {
                    window.clearInterval(self.interval);
                    self.finish();
                }
            }), 1000);
            document.cookie = 'connector_oauth_popup=1; path=/';
        }
        Connector.prototype.finish = function() {
            window.location = "/connector/index";
        };
        return Connector;
    })();

    $(document).ready(function() {
        var connector_btn = $('.addConnector');
        $(connector_btn).each(function(i, e) {
            var connector_connect = new Connector($(e).attr('href'));
            $(e).on('click', function(e) {
                e.preventDefault();
                connector_connect.exec();
            });
        });
    });
</script>

<div class="row">
    <div class="large-12 columns">
        <?php echo $this->partial('/partial/flashmessages'); ?>
    </div>
</div>

<div class="row">
    <div class="large-1 columns">add:</div>
    <div class="large-2 columns">
        <a href="/connector/twitter" class="small button addConnector">twitter</a>
    </div>
    <div class="large-2 columns">
        <a href="/connector/foursquare" class="small button addConnector">foursquare</a>
    </div>
    <div class="large-2 columns">
        <a href="javascript:ConnectorFacebook();" class="small button">facebook</a>
    </div>
    <div class="large-2 columns">
        <a href="/connector/instagram" class="small button addConnector">instagram</a>
    </div>
</div>

<?php foreach ($this->auth()->getIdentity()->getConnectors() as $connector) : ?>
    <div class="row">
        <div class="large-3 columns" style="padding: 7px 0px;">
            <?php echo $connector->getType(); ?>
        </div>
        <div class="large-3 columns" style="padding: 7px 0px;">
            <?php echo $connector->getName(); ?>
        </div>
        <div class="large-6 columns">
            <a class="small button" href="/connector/delete/connectorId/<?php echo $connector->getId(); ?>">delete</a>
        </div>
    </div>
<?php endforeach; ?>