<script type="text/javascript">
    var QueryString = function () {
        var query_string = {};
        var query = window.location.hash.substring(1);
        var vars  = query.split("&");
        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (typeof query_string[pair[0]] === "undefined") {
                query_string[pair[0]] = pair[1];
            } else if (typeof query_string[pair[0]] === "string") {
                var arr = [ query_string[pair[0]], pair[1] ];
                query_string[pair[0]] = arr;
            } else {
                query_string[pair[0]].push(pair[1]);
            }
        }
        return query_string;
    }();

    if (typeof QueryString.access_token) {
        window.location = "/confirm?state=" + QueryString.state + "&access_token=" + QueryString.access_token;
    }
</script>