<?php echo $this->partial('/partial/flashmessages'); ?>

<script>
var settings = {
    app_id      : '<?php echo $this->config['facebook']['app_id']; ?>',
    app_redirect: '<?php echo $this->config['facebook']['callback_url']; ?>',
    app_scope   : '<?php echo $this->config['facebook']['scope']; ?>',
    newspaper_id: '<?php echo $this->newspaper->getId(); ?>'
};
</script>
<script src="/js/facebook.js"></script>

<a href='#' id='fb-invite'>inviteer uw familie</a>