<div class="row">
    <div class="large-4 large-offset-4 columns">
        <?php echo $this->partial('/partial/flashmessages'); ?>
    </div>
</div>

<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId   : '<?php echo $this->config['facebook']['app_id']; ?>',
            frictionlessRequests : true
        });
    };

    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    function ConnectorFacebook() {
        FB.ui({
            method  : 'apprequests',
            message : 'Nodig je familie uit...'
        }, function(response) {
            if (response.to) {
                window.location = "/invite/newspaperId/<?php echo $this->newspaper->getId(); ?>?" + $.param(response);
            } else {
                console.log('User cancelled login or did not fully authorize.');
            }
        });
    }
</script>

<a href="javascript:ConnectorFacebook();">invite</a>