<?php
    $form = $this->form;
    $form->prepare();
?>

<div class="row">
    <div class="large-4 large-offset-4 columns">
        <?php echo $this->partial('/partial/flashmessages', array('form' => $form)); ?>
    </div>
</div>

<?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="large-4 large-offset-4 columns">
            <?php echo $this->formRow($form->get('email'), null, true); ?>
        </div>
    </div>
    <div class="row">
        <div class="large-4 large-offset-4 columns">
            <?php echo $this->formRow($form->get('password'), null, false); ?>
        </div>
    </div>
    <div class="row">
        <div class="large-4 large-offset-4 columns">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>

<div class="row">
    <div class="large-4 large-offset-4 columns">
        <a href="/passwordforgotten">password forgotten</a> or, <a href="/signup">new user?</a>
    </div>
</div>