<p>Hello</p>

<h3>Please click on the link below to reset your password. If you did not request a password reset, please ignore this email.</h3>

<p><a href="<?php echo $this->resetLink; ?>"><?php echo $this->resetLink; ?></a></p>

<p>If you have any questions, please don't hesitate to contact us! You can email us at <a href="mailto:support@marketingappexchange.com">support@marketingappexchange.com</a> or call us at (202) 640-5910.</p>

<p>Thank You!</p>
<p>Your Friends at the MarketingAppExchange</p>