<?php if ($this->inviter == null) : ?>
    <h3>Congratulations! You are one step closer to making your marketing world much easier to manage!</h3>
<?php else: ?>
    <p>Hi there!</p>
    <p>You have been invited by <?php echo $this->inviter; ?> to visit the MarketingAppExchange.'</p>
<?php endif; ?>

<p>We have created a new MarketingAppExchange account that is ready to be activated.<br />
    Your account has been created with the username <?php echo $this->email; ?></p>

<p>To activate your account please use the following link: <a href="<?php echo $this->registerLink; ?>"><?php echo $this->registerLink; ?></a></p>

<p>Thank you!</p>
<p>Your Friends at the MarketingAppExchange</p>
