<div class="one_half">
    <h1>Fantastisch! Je bent aangemeld.</h1>
    <h2>Waarheen sturen we het wekelijkse krantje?</h2>
</div>
<div class="one_half last">
    <div class="counters-circle clearfix">
        <script type='text/javascript'>
            jQuery(document).ready(function() {
                var opts = {
                    lines: 12, // The number of lines to draw
                    angle: 0.5, // The length of each line
                    lineWidth: 0.05, // The line thickness
                    colorStart: '#50cbf4', // Colors
                    colorStop: '#50cbf4', // just experiment with them
                    strokeColor: '#f6f6f6', // to see which ones work best for you
                    generateGradient: false
                };
                var gauge_1 = new Donut(document.getElementById('counter-circle-1')).setOptions(opts); // create sexy gauge!
                gauge_1.maxValue = 100; // set max gauge value
                gauge_1.animationSpeed = 128; // set animation speed (32 is default value)
                gauge_1.set(60); // set actual value
            });
        </script><div class="counter-circle-wrapper"><canvas width="220" height="220" class="counter-circle" id="counter-circle-1"></canvas><div class="counter-circle-content">50%</div></div>
    </div>
</div>
<div class="clearboth"></div>
<div class="fullwidth-box" style="background-color:#ffffff;background-image:url();background-repeat:no-repeat;background-position:top left;background-attachment:scroll;border-top:0px solid #f6f6f6;border-bottom:0px solid #f6f6f6;padding-top:0px;padding-bottom:0px;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;"><div class="avada-row"></div></div>

<div style='width:50%;'>
    <?php
        $form = $this->form;
        $form->prepare();

        $this->formRow()->setInputErrorClass('error');
    ?>

    <?php echo $this->partial('/partial/flashmessages', array('form' => $form)); ?>


    <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formRow($form->get('name'), null, false); ?>
        <?php echo $this->formRow($form->get('street'), null, false); ?>
        <?php echo $this->formRow($form->get('number'), null, false); ?>
        <?php echo $this->formRow($form->get('zipcode'), null, false); ?>
        <?php echo $this->formRow($form->get('city'), null, false); ?>
        <?php echo $this->formRow($form->get('email'), null, false); ?>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>