<p style="text-align: center;"><a class="button large default" href="/feed/pdf" target="_blank" id="fb-login">Stuur het op</a></p>

<div id="newspaper" class="clearfix">

    <div class="header">
        <img src="/images/nieuwsbrief_header.png" />
        <p class="family">Familie Peters Antwerpen 22/27</p>
    </div>
    
    
<?php $feed = $this->fbPhotoFeed->getPhotoFeed(); 
      $i = 0; 
      $y = 1;
      while($i < 4 && list($key, $photo) = each($feed)): 
?>
    
    <div class="item">
        <img src="<?php echo $photo['images'][0]['source']; ?>"></img>
        <p class="when">Xavier Vermeiren Zondag 1/12/2013</p>
        <p class="title"><?php if(isset($photo['name'])) echo $photo['name']; ?></p>
    </div>
    
<?php $i++; 
      endwhile; 
?>

</div>

<p style="text-align: center;"><a class="button large default" href="/feed/pdf" target="_blank" id="fb-login">Stuur het op</a></p>